### ISSUE TITLE
Game crashes instantly with this mod

### ISSUE THREAD

**Issue by OblivionHeart** [vini2003/Body-Shuffle#4]
![image](https://user-images.githubusercontent.com/80137658/110191343-cde92400-7df5-11eb-8d35-6136a5cbe73c.png)

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'blade'!
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
	at net.minecraft.class_310.<init>(class_310.java:437)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
Caused by: java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at vini2003.xyz.blade.Blade.<clinit>(Blade.java:19)

idk what this is but it should help

**Comment by vini2003** [comment]
See #3, mistake on my end.
